# ##################################################### #
#                                                       #
# Docker-compose file for Inception                     #
#                                                       #
# ##################################################### #

# VERSION:
#
# Compose file의 버전
# docker-compose의 버전에 따라 사용할 수 있는 compose file 버전이 다르다. 도커-컴포즈 1.27.0 버전 이후부터는 2.x와 3.x가 사용 가능.
version: '3.0'

# SERVICES:
#
# service를 정의하여 격리된 환경에서 컨테이너들을 함께 실행한다.
services:
  nginx:
    build: ./requirements/nginx/    # 빌드할 Dockerfile 위치
    image: nginx
    # 조건에 관계없이 서비스를 활성 상태로 유지하기 위한 재시작 정책 -> https://serverfault.com/questions/884759/how-does-restart-always-policy-work-in-docker-compose
    # 어떤 이유로든 컨테이너가 종료되었을 경우, 재시작을 위한 설정이다.
      # always : 컨테이너를 수동으로 끄기 전까지 항상 재시작
    restart: always
    volumes:
      - wp_volume:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    #environment:
    # Dockerfile의 각종 환경변수를 설정하는 ENV 옵션과 동일하다.
    # environment로 바로 환경 변수를 설정할 수 있지만, env_file 옵션으로 파일을 읽어 올 수 있다.
      # env_file의 파일명을 .txt 등의 확장자로 만들어도 되지만, 도커 공식 가이드에 따라 .env를 쓰는 게 좋다.
    networks:
      - inception_net
    tty: true
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - db_volume:/var/lib/mysql/   #[호스트 디렉토리]:[컨테이너 디렉토리]
    env_file:
      - .env
    networks:
      - inception_net
    tty: true
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp_volume:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception_net

# VOLUMES:
#
# 컨테이너에서 사용하는 volume 설정으로 대체 가능(옵션)
volumes:
  db_volume:
    driver: local
    driver_opts:    #driver_opts: linux 명령어 mount에 의존한다.
      type: none
      device: /home/jji/data/mariadb
      o: bind
      #volume을 bind로 묶어줘야 docker가 내 volume을 찾을 수 있다.
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/jji/data/wordpress
      o: bind

# NETWORKS:
#
#
networks:
  inception_net:
    driver: bridge


